Implement Bell's index of isolation
vengroff/divintseg pull request #36
Opened 2023-08-07 18:31 UTC by corey53w53

Hi Darren, I hope you are doing well! I had some questions regarding the implementation of bell's index that I wanted to run by you.

Firstly, Bell's index is another index of isolation, which we already have, so instead of having it be a completely separate function, should we instead make some argument for isolation that allows the user to specify the original implementation of isolation or Bell's index? Currently I have them as two separate function (isolation and bells) but it would be pretty simply to combine them into one. 

Secondly, Bell's index is invalid when then entire region contains of the `group_name` argument, because this causes the formula to divide by 0 which yields NaN. Currently, I have been filling these with 1 because when an entire region is populated by a single group, it would mean that there is complete segregation (which is what a 1 represents). Running the Dataframe on the original isolation function also yields 1, so I thought it made sense to do the same for Bells. I was wondering if there was a better way I could take care of this, maybe stating as a prerequisite that an entire region cannot be `group_name`?

Thank you so much in advance!

2023-08-16 19:01 UTC, vengroff commented
I think it's fine to leave them as two separate functions. And I like the idea of 1 instead of NaN in the completely homogeneous case, with the caveat that the documentation should make that behavior clear.

2023-08-16 19:04 UTC, vengroff requested changes

2023-08-16 19:04 UTC, vengroff commented on divintseg/_core.py
> +        with respect to all of the other columns in the data frame.
I would just add a comment here explaining that 1 is returned in the homogeneous case.

2023-08-17 17:58 UTC, corey53w53 commented
Hi Darren, I changed the documentation accordingly, please let me know if there are any other revisions you would like to see for this function. Thank you so much in advance!

2023-08-18 13:33 UTC, vengroff approved these changes

2023-08-18 13:34 UTC, merged